name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Test
      run: npm test
    
    - name: Build Android
      run: |
        cd android
        ./gradlew assembleDebug
    
    - name: Build iOS
      run: |
        cd ios
        pod install
        xcodebuild -workspace thdWikiMobile.xcworkspace -scheme thdWikiMobile -configuration Debug -sdk iphonesimulator 